"""added sound settings

Revision ID: 0468719a1370
Revises: a08e713559a7
Create Date: 2025-01-17 12:28:26.672637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0468719a1370'
down_revision = 'a08e713559a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sound_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selected_sound', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sound_settings')
    # ### end Alembic commands ###
