"""new table3

Revision ID: 120503b586aa
Revises: 0aa7584f441b
Create Date: 2025-01-14 22:23:15.016656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120503b586aa'
down_revision = '0aa7584f441b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('elapsed_time', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timer_data')
    # ### end Alembic commands ###
