"""added classes

Revision ID: a08e713559a7
Revises: 120503b586aa
Create Date: 2025-01-16 14:48:09.334390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08e713559a7'
down_revision = '120503b586aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pomodoro', sa.Integer(), nullable=True),
    sa.Column('short_break', sa.Integer(), nullable=True),
    sa.Column('long_break', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    op.drop_table('timer_settings')
    # ### end Alembic commands ###
