"""new

Revision ID: cd1fa46c7319
Revises: bd3bb3207dc6
Create Date: 2025-01-14 20:53:53.679477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1fa46c7319'
down_revision = 'bd3bb3207dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer_data', schema=None) as batch_op:
        batch_op.drop_constraint('timer_data_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('timer_data_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
